// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/25       [336409]
Creator        : tbales
Date           : Sat Jun  6 10:51:42 2015
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-504.1.3.el6.x86_64 #1 SMP Wed Nov 12 06:58:35 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /direct/usatlas+u/tbales/PivotDataScienceExercise/Sandbox
Training events: 400
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "50" [Number of training cycles]
HiddenLayers: "10,10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
ConsExp_marital               ConsExp_marital               ConsExp_marital               ConsExp_marital                                                 'F'    [1,5]
ConsExp_foodhome              ConsExp_foodhome              ConsExp_foodhome              ConsExp_foodhome                                                'F'    [715,14952]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "ConsExp_marital", "ConsExp_foodhome" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[11][3];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[11][11];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][11];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 3; fWeights[0] = new double[3]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 11; fWeights[2] = new double[11]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = nan;
   fWeightMatrix0to1[1][0] = -nan;
   fWeightMatrix0to1[2][0] = nan;
   fWeightMatrix0to1[3][0] = nan;
   fWeightMatrix0to1[4][0] = nan;
   fWeightMatrix0to1[5][0] = -nan;
   fWeightMatrix0to1[6][0] = -nan;
   fWeightMatrix0to1[7][0] = -nan;
   fWeightMatrix0to1[8][0] = -nan;
   fWeightMatrix0to1[9][0] = -nan;
   fWeightMatrix0to1[0][1] = nan;
   fWeightMatrix0to1[1][1] = -nan;
   fWeightMatrix0to1[2][1] = nan;
   fWeightMatrix0to1[3][1] = nan;
   fWeightMatrix0to1[4][1] = nan;
   fWeightMatrix0to1[5][1] = -nan;
   fWeightMatrix0to1[6][1] = -nan;
   fWeightMatrix0to1[7][1] = -nan;
   fWeightMatrix0to1[8][1] = -nan;
   fWeightMatrix0to1[9][1] = -nan;
   fWeightMatrix0to1[0][2] = nan;
   fWeightMatrix0to1[1][2] = -nan;
   fWeightMatrix0to1[2][2] = nan;
   fWeightMatrix0to1[3][2] = nan;
   fWeightMatrix0to1[4][2] = nan;
   fWeightMatrix0to1[5][2] = -nan;
   fWeightMatrix0to1[6][2] = -nan;
   fWeightMatrix0to1[7][2] = -nan;
   fWeightMatrix0to1[8][2] = -nan;
   fWeightMatrix0to1[9][2] = -nan;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -nan;
   fWeightMatrix1to2[1][0] = -nan;
   fWeightMatrix1to2[2][0] = -nan;
   fWeightMatrix1to2[3][0] = -nan;
   fWeightMatrix1to2[4][0] = -nan;
   fWeightMatrix1to2[5][0] = -nan;
   fWeightMatrix1to2[6][0] = -nan;
   fWeightMatrix1to2[7][0] = -nan;
   fWeightMatrix1to2[8][0] = -nan;
   fWeightMatrix1to2[9][0] = -nan;
   fWeightMatrix1to2[0][1] = -nan;
   fWeightMatrix1to2[1][1] = -nan;
   fWeightMatrix1to2[2][1] = -nan;
   fWeightMatrix1to2[3][1] = -nan;
   fWeightMatrix1to2[4][1] = -nan;
   fWeightMatrix1to2[5][1] = -nan;
   fWeightMatrix1to2[6][1] = -nan;
   fWeightMatrix1to2[7][1] = -nan;
   fWeightMatrix1to2[8][1] = -nan;
   fWeightMatrix1to2[9][1] = -nan;
   fWeightMatrix1to2[0][2] = -nan;
   fWeightMatrix1to2[1][2] = -nan;
   fWeightMatrix1to2[2][2] = -nan;
   fWeightMatrix1to2[3][2] = -nan;
   fWeightMatrix1to2[4][2] = -nan;
   fWeightMatrix1to2[5][2] = -nan;
   fWeightMatrix1to2[6][2] = -nan;
   fWeightMatrix1to2[7][2] = -nan;
   fWeightMatrix1to2[8][2] = -nan;
   fWeightMatrix1to2[9][2] = -nan;
   fWeightMatrix1to2[0][3] = -nan;
   fWeightMatrix1to2[1][3] = -nan;
   fWeightMatrix1to2[2][3] = -nan;
   fWeightMatrix1to2[3][3] = -nan;
   fWeightMatrix1to2[4][3] = -nan;
   fWeightMatrix1to2[5][3] = -nan;
   fWeightMatrix1to2[6][3] = -nan;
   fWeightMatrix1to2[7][3] = -nan;
   fWeightMatrix1to2[8][3] = -nan;
   fWeightMatrix1to2[9][3] = -nan;
   fWeightMatrix1to2[0][4] = -nan;
   fWeightMatrix1to2[1][4] = -nan;
   fWeightMatrix1to2[2][4] = -nan;
   fWeightMatrix1to2[3][4] = -nan;
   fWeightMatrix1to2[4][4] = -nan;
   fWeightMatrix1to2[5][4] = -nan;
   fWeightMatrix1to2[6][4] = -nan;
   fWeightMatrix1to2[7][4] = -nan;
   fWeightMatrix1to2[8][4] = -nan;
   fWeightMatrix1to2[9][4] = -nan;
   fWeightMatrix1to2[0][5] = -nan;
   fWeightMatrix1to2[1][5] = -nan;
   fWeightMatrix1to2[2][5] = -nan;
   fWeightMatrix1to2[3][5] = -nan;
   fWeightMatrix1to2[4][5] = -nan;
   fWeightMatrix1to2[5][5] = -nan;
   fWeightMatrix1to2[6][5] = -nan;
   fWeightMatrix1to2[7][5] = -nan;
   fWeightMatrix1to2[8][5] = -nan;
   fWeightMatrix1to2[9][5] = -nan;
   fWeightMatrix1to2[0][6] = -nan;
   fWeightMatrix1to2[1][6] = -nan;
   fWeightMatrix1to2[2][6] = -nan;
   fWeightMatrix1to2[3][6] = -nan;
   fWeightMatrix1to2[4][6] = -nan;
   fWeightMatrix1to2[5][6] = -nan;
   fWeightMatrix1to2[6][6] = -nan;
   fWeightMatrix1to2[7][6] = -nan;
   fWeightMatrix1to2[8][6] = -nan;
   fWeightMatrix1to2[9][6] = -nan;
   fWeightMatrix1to2[0][7] = -nan;
   fWeightMatrix1to2[1][7] = -nan;
   fWeightMatrix1to2[2][7] = -nan;
   fWeightMatrix1to2[3][7] = -nan;
   fWeightMatrix1to2[4][7] = -nan;
   fWeightMatrix1to2[5][7] = -nan;
   fWeightMatrix1to2[6][7] = -nan;
   fWeightMatrix1to2[7][7] = -nan;
   fWeightMatrix1to2[8][7] = -nan;
   fWeightMatrix1to2[9][7] = -nan;
   fWeightMatrix1to2[0][8] = -nan;
   fWeightMatrix1to2[1][8] = -nan;
   fWeightMatrix1to2[2][8] = -nan;
   fWeightMatrix1to2[3][8] = -nan;
   fWeightMatrix1to2[4][8] = -nan;
   fWeightMatrix1to2[5][8] = -nan;
   fWeightMatrix1to2[6][8] = -nan;
   fWeightMatrix1to2[7][8] = -nan;
   fWeightMatrix1to2[8][8] = -nan;
   fWeightMatrix1to2[9][8] = -nan;
   fWeightMatrix1to2[0][9] = -nan;
   fWeightMatrix1to2[1][9] = -nan;
   fWeightMatrix1to2[2][9] = -nan;
   fWeightMatrix1to2[3][9] = -nan;
   fWeightMatrix1to2[4][9] = -nan;
   fWeightMatrix1to2[5][9] = -nan;
   fWeightMatrix1to2[6][9] = -nan;
   fWeightMatrix1to2[7][9] = -nan;
   fWeightMatrix1to2[8][9] = -nan;
   fWeightMatrix1to2[9][9] = -nan;
   fWeightMatrix1to2[0][10] = -nan;
   fWeightMatrix1to2[1][10] = -nan;
   fWeightMatrix1to2[2][10] = -nan;
   fWeightMatrix1to2[3][10] = -nan;
   fWeightMatrix1to2[4][10] = -nan;
   fWeightMatrix1to2[5][10] = -nan;
   fWeightMatrix1to2[6][10] = -nan;
   fWeightMatrix1to2[7][10] = -nan;
   fWeightMatrix1to2[8][10] = -nan;
   fWeightMatrix1to2[9][10] = -nan;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -nan;
   fWeightMatrix2to3[0][1] = -nan;
   fWeightMatrix2to3[0][2] = -nan;
   fWeightMatrix2to3[0][3] = -nan;
   fWeightMatrix2to3[0][4] = -nan;
   fWeightMatrix2to3[0][5] = -nan;
   fWeightMatrix2to3[0][6] = -nan;
   fWeightMatrix2to3[0][7] = -nan;
   fWeightMatrix2to3[0][8] = -nan;
   fWeightMatrix2to3[0][9] = -nan;
   fWeightMatrix2to3[0][10] = -nan;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
